### ISSUE TITLE
Add fallback styles

### ISSUE THREAD

**Issue by studiofranzwalter** [studiofranzwalter/franzwalter.com#4]
### Tasks 

- [x] No grid support
- [x] No custom properties support
- [x] No stylesheets at all
