### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by studiofranzwalter** [studiofranzwalter/franzwalter.com#5]
### Tasks 

- [ ] Update color scheme
- [ ] Update font weight(s)
- [ ] Update contrast ratios
